### ISSUE TITLE
C1S4 - A gamer/guest I should be able to start or restart a new game and see a list of words that can be formed during game play

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#167]
Success: 
I should be able to keep playing indefinitely with no maximum level, and there is a different criteria for each level, which is auto generated

Failure:
I have finished all the words in the database 

Tasks:

1- Sequence Diagram @Khloud-Khalid 
2- Documentation @mostafahassaan 
3- Research
4- Implementation @adamggg 
5- Testing @KareemAliRahman

**Comment by Khloud-Khalid** [comment]
@zoheiry 
you should write the name of the class rather than the name of method.
why is there an arrow from newGame() to startGame() with no description?
does the home view stay open after calling the choose language of choice method?
does the setLang() method keep working after calling the newGame method?
alt box should not include get unvoted keywords()
does the get unvoted keywords() method keep working after returning false?
does the startGame() method keep working after calling setLevelAttributes?
same for setLevelAttributes and get_unvoted_keywords

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by mostafahassaan** [comment]
Zozo I'm having trouble with pulling or pushing anything right now. I'll review tests in a bit :)

**Comment by zoheiry** [comment]
try to make it before 12 please, cause i need to make sure everything is on
master and functional before i sleep, or else i wont be able to

**Comment by adamggg** [comment]
@zoheiry code reopened with very small issues, almost verified =)

**Comment by mostafahassaan** [comment]
All jasmine tests pass, verified :)

**Comment by mostafahassaan** [comment]
Had to reopen for docs. nextValidEnty() documentation is missing

**Comment by zoheiry** [comment]
added please review

**Comment by mostafahassaan** [comment]
verified

**Comment by adamggg** [comment]
code verified =)

**Comment by krmali** [comment]
@zoheiry, there is a popover window that appears after wining the second level which cannot be closed in the arabic site part.

**Comment by zoheiry** [comment]
That never happens with me O.o

**Comment by krmali** [comment]
@zoheiry, when it appeared to me once and stayed there even after going to the next vote form and even after going to the next level. the popover is about "اسرع، ستصل الي القمة"

**Comment by krmali** [comment]
@zoheiry, where do you use it?

**Comment by zoheiry** [comment]
Don't worry I'll fix it

**Comment by krmali** [comment]
@zoheiry, scenario verified
