### ISSUE TITLE
[C3.S28] As a developer I should be able to add words and their synonom and change the synonym to a project in project page

### ISSUE THREAD

**Issue by krmali** [MGhanem/smartsoft-13#353]
Success:
there should be a row to add new keywords to project. When the user enters a keyword using autocomplete and synonyms will be shown as a dropdown sorted using the project criteria. 

Failure:
If no keyword was found, redirect to keyword add page. If no synonyms were found the keyword should not be added.

Scenario Reviewer: @m0hamed
Implementation Reviewer: @adamggg 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by zoheiry** [comment]
Docs all good, verified.

**Comment by krmali** [comment]
@Khloud-Khalid , @adamggg  please review.

**Comment by krmali** [comment]
@m0hamed please review scenario

**Comment by adamggg** [comment]
Check the comments that I have left on the pull request please :smile:

**Comment by krmali** [comment]
@adamggg , fixed

**Comment by m0hamed** [comment]
so where exactly is the pull request

**Comment by m0hamed** [comment]
also we are still in talks about adding more parameters to a project like the country being targeted and the educational level so you may need to add that to the way you order the synonyms

**Comment by krmali** [comment]
@m0hamed ,pull no. 414

**Comment by m0hamed** [comment]
I cant add a word to a project using auto complete every-time I press tab the input field clears. Also the inputs should be vertically in the middle of the row.

**Comment by krmali** [comment]
@m0hamed ,fixed the problem with the css and autocomplete

**Comment by krmali** [comment]
@Khloud-Khalid , please review UML

**Comment by m0hamed** [comment]
remove the alert and remove the search button "the one with the binoculars" since you get the synonyms automatically. also when there are no synonyms change the add to project to follow word. you could do a get request to the follow route. its in the routes file just ajax it the same way you ajaxed the rest

**Comment by krmali** [comment]
@m0hamed , Now the alert is removed and for the follow part , this is not included in the story description.

**Comment by m0hamed** [comment]
ok then disable the add to project button

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman the arrow with drop down with sorted keywords criteria should be shifted down a bit since it doesn't happen at the same time of the add word action so they shouldn't be on the same line. Also, the second alt box should be completely included in the first if they are nested conditions rather than having a part of it outside the first box.

**Comment by zoheiry** [comment]
tests verified

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by m0hamed** [comment]
please remove the search button and disable the add to project button when there are no synonyms also when a word is added or a synonym is removed you should show a message to the user since if you try to add a new word the synonym would be changed rather than added at the bottom of the list which may not be visible to the user.

**Comment by m0hamed** [comment]
missing translation "Synonym changed successfully"

**Comment by m0hamed** [comment]
verified but please pull master

**Comment by krmali** [comment]
@adamggg, please review.

**Comment by zoheiry** [comment]
Docs Verified

**Comment by adamggg** [comment]
@KareemAliRahman You still haven't fixed some of my comments on the pull request =)

**Comment by krmali** [comment]
@adamggg, please review

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by zoheiry** [comment]
Docs verified once more

**Comment by zoheiry** [comment]
all tests good, Verified
