### ISSUE TITLE
As a Developer, I can use the api to translate words dynamically according to filtering criteria

### ISSUE THREAD

**Issue by m0hamed** [MGhanem/smartsoft-13#363]
Success: Send keyword and filtering criteria, get synonyms based on sent data using authentication token.
Failure: No synonym found. or wrong authentication token

documentation and test: @mostafahassaan 
implementation: @NourhanMohamed 
uml: @nourhanZ 
scenario: @KareemAliRahman

**Comment by m0hamed** [comment]
@NourhanMohamed, @mostafahassaan please review

**Comment by NourhanMohamed** [comment]
check back comments on pull request .. 
I loved your code anyways .. CLEAN! :+1:

**Comment by krmali** [comment]
@m0hamed, good work Ashraf
here are my comments for now:
1-in the API page, there is a weird line: Geocoder::Result::Freegeoip:0x0000....., this is obviously should not appear.
2- the help page is not refined in arabic website, at least make it like the english help page.
3- you misspelled the donot make it "do not" :), in the line after HEADS UP in the help page

**Comment by mostafahassaan** [comment]
@m0hamed test and docs verified :D good going chiko.

**Comment by m0hamed** [comment]
@NourhanMohamed please review again.

**Comment by NourhanMohamed** [comment]
check pull request comments =)

**Comment by nourhanZ** [comment]
where is the UML?!!

**Comment by m0hamed** [comment]
@NourhanMohamed and @KareemAliRahman please review again. also @nourhanZ I never set it to UML pending. the uml is still pending construction

**Comment by NourhanMohamed** [comment]
I did review and reopened .. no changes are done and my comments are still there

**Comment by nourhanZ** [comment]
The UML is really GOOD but I have some comments:
1) Separate the data type and name with colon
2) the return type Synonym synonym should be just Synonym as you just write the return type
3) In the third case in request when you use the retrieve_synonym method you must indicate that you return the most voted one not all the array just use .first
4) Why do you make the return type between API_Javascript and API_controller solid?!! it must be dashed
5) In the second case when generating an API key I think you should indicate the the project related to this key is optional and instead of presses generate make it clicks[generate] same goes for delete
6) the empty return line in the delete case it's either missing the return on it or it's redundant and should be removed
Fix this comments and tag me again :)

**Comment by nourhanZ** [comment]
UML verified =)

**Comment by m0hamed** [comment]
@NourhanMohamed @KareemAliRahman please review

**Comment by krmali** [comment]
@m0hamed, change the translation of "generate" in the arabic page to "اصدار" instead of "توليد"

**Comment by krmali** [comment]
@m0hamed , scenario verified

**Comment by NourhanMohamed** [comment]
code verified

**Comment by NourhanMohamed** [comment]
@m0hamed don't forget to close this issue =)
